'use strict';
const crypto = require('crypto');
const transitions = { intake: ['vehicle_bound'], vehicle_bound: ['evidence_validated'], evidence_validated: ['owner_review', 'closed'], owner_review: ['approved', 'closed'], approved: ['command_queued'], command_queued: ['acknowledged', 'failed'], acknowledged: ['closed', 'recovered'], failed: ['command_queued', 'recovered'], recovered: ['closed'], closed: [] };
const perms = { owner: ['read', 'create', 'approve'], technician: ['read', 'diagnose', 'recover'], operator: ['read', 'dispatch', 'recover'], admin: ['read', 'create', 'approve', 'diagnose', 'dispatch', 'recover', 'configure'] };
const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.keys(v).sort().reduce((out,key)=>{out[key]=canonical(v[key]);return out;},{}):v;
const hash = v => crypto.createHash('sha256').update(JSON.stringify(canonical(v))).digest('hex');
function requireScope(actor, tenantId, vehicleId, action) { if (!actor || actor.tenantId !== tenantId) throw new Error('tenant_scope_denied'); if (actor.vehicleIds !== '*' && !(actor.vehicleIds || []).includes(vehicleId)) throw new Error('vehicle_scope_denied'); if (!(perms[actor.role] || []).includes(action)) throw new Error('role_scope_denied'); }
function validateRequest(input) { for (const f of ['vehicleId', 'vin', 'manualVersion', 'requestType', 'ownerId', 'consent']) if (!input[f]) throw new Error(`missing_${f}`); if (!Array.isArray(input.evidence) || !input.evidence.length) throw new Error('evidence_required'); if (!input.consent.processing || !input.consent.purpose || !Number.isInteger(input.consent.retentionDays) || input.consent.retentionDays<1 || input.consent.retentionDays>3650) throw new Error('valid_consent_and_retention_required'); return { ...input, inputHash: hash(input), state: 'evidence_validated' }; }
function transition(current, target, ctx = {}) { if (!(transitions[current] || []).includes(target)) throw new Error('invalid_transition'); if (target === 'approved' && (!ctx.humanApprovalId || !ctx.approverId)) throw new Error('human_approval_required'); if (target === 'command_queued' && ctx.consequential && !ctx.humanApprovalId) throw new Error('consequential_action_requires_approval'); if (target === 'acknowledged' && !ctx.providerReceiptId) throw new Error('provider_receipt_required'); return target; }
function adapterDelivery(adapter, payload, idempotencyKey, receipt) { if (!['BMW_CONNECTEDDRIVE', 'SERVICE_SHOP', 'PARTS_RETAILER', 'RECALL_FEED', 'NOTIFICATION'].includes(adapter)) throw new Error('unsupported_adapter'); if (!idempotencyKey) throw new Error('idempotency_key_required'); const payloadHash = hash(payload); if (receipt && receipt.payloadHash !== payloadHash) throw new Error('receipt_payload_mismatch'); return { adapter, payloadHash, idempotencyKey, state: receipt ? 'confirmed' : 'queued' }; }
function evaluate(result, limits) { const resultFields=['correctness','safetyRecall','latencyMs','outcomeSuccess'];const limitFields=['correctness','latencyMs','outcomeSuccess'];if(resultFields.some(key=>!Number.isFinite(result[key]))||limitFields.some(key=>!Number.isFinite(limits[key])))throw new Error('complete_finite_evaluation_required');const failures = []; if (result.correctness < limits.correctness) failures.push('correctness'); if (result.safetyRecall < 1) failures.push('safety'); if (result.latencyMs > limits.latencyMs) failures.push('latency'); if (result.outcomeSuccess < limits.outcomeSuccess) failures.push('outcome'); return { accepted: !failures.length, failures, resultHash: hash({ result, limits }) }; }
module.exports = { hash, requireScope, validateRequest, transition, adapterDelivery, evaluate };
